changelog:
  categories:
    - title: ✨ Features
      labels:
        - feat
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: 📚 Documentation
      labels:
        - docs
        - documentation
    - title: 🔧 Maintenance
      labels:
        - chore
        - ci
        - build
        - refactor
    - title: ⚡ Performance
      labels:
        - performance
        - optimization
    - title: 🔒 Security
      labels:
        - security
        - vulnerability
  exclude:
    labels:
      - ignore-for-release
      - wip
      - do-not-merge
