blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/your-org/enterprise-agent/wiki
    about: Check our documentation for usage guides and examples
  - name: 💬 Discussions
    url: https://github.com/your-org/enterprise-agent/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/your-org/enterprise-agent/security/advisories/new
    about: Report security vulnerabilities privately